### ISSUE TITLE
partial implementation of feature i requested

### ISSUE THREAD

**Issue by ghost** [AssassinsCreedRemastered/Assassins-Creed-Remastered-Launcher#3]
i requested the feature of being able to change the games directory when i cut and paste the game directory to some other location and it seems u did a good job in changing your  source code to adapt and reassign the working directory by rewriting the path.txt in %appdata%\Ubisoft\blah blah directory which was a great move but u forgot to also reassign the new directory for the umod settings as well. Namely these files are uMod_SaveFiles.txt and uMod_Settings.txt i guess ? maybe. anyways the launcher cant seem to find the configuration for umod for the game in the new location such as the templates, textrue saving directory and the tpf files that are being loaded despite me manually specifying the new location in these text files so it must mean the source code for the launcher cant identify the new location of templates and tpf files for the game in umod . I congratulate ur efforts in improving the launcher but it seems it was only partially implemented. next time dont just try launching the game from a diferent directory, please see to it that umod is working alongside from the new location as well. Again thanks for heeding my request and improving the launcher and liked what you did so far. just a teeny correction and ull get it right ; ). last but not least, mention ur enhancements at nexusmods as well.

**Comment by shazzaam7** [comment]
I have implemented uMod settings transfer too, but forgot to make it execute if Path.txt doesn't exist. Fixed it in 63b4830 commit. Should be live soon.

**Comment by ghost** [comment]
> I have implemented uMod settings transfer too, but forgot to make it execute if Path.txt doesn't exist. Fixed it in [63b4830](https://github.com/AssassinsCreedRemastered/Assassins-Creed-Remastered-Launcher/commit/63b4830b5653551f6de37520486955fe3ceacf59) commit. Should be live soon.

Great job brother. U inspire me. I am a junior software developer and intermediate level web developer but not half as good as you. I somewhat was able to understand bits and pieces of your source code and tried fixing it myself, but what to do bro im just a noob lol : ). Anyways i think u fixed it and im now trying to improve my c# skills from what u implemented. thanks for keeping this open source so others can learn as well. i hope you will improve your ac2 project in a similar fashion when u get time.
